{% set name = "install-jdk" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 2bfd53caf660e4916df0215a5715519dcb9547fa2a5f07421fd97a8046851eaa

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }},<4.0

test:
  imports:
    - jdk
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jyksnw/install-jdk
  summary: Installs AdoptOpenJDK Java
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - rxm7706
