{% set name = "install-jdk" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 25c1a78c1531d28a47361dafd2d31bfae7db5b4a3fc14ea5f5eda438216be8a1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - jdk
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jyksnw/install-jdk
  summary: Installs AdoptOpenJDK Java
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - rxm7706
