{% set name = "install-jdk" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: ef850b42a011ff1dbae34698b31ead1a21c060079723bf0d83a52dd276400002

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - jdk
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jyksnw/install-jdk
  summary: Installs AdoptOpenJDK Java
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - rxm7706
