{% set name = "install-jdk" %}
{% set version = "1.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 51786cf98f7c5f7223e08213200dde839a5d526150b635e86c42a422b087f8e1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.8,<4.0

test:
  imports:
    - jdk
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jyksnw/install-jdk
  summary: Installs AdoptOpenJDK Java
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - rxm7706
